"""update models

Revision ID: abe7b49e64f7
Revises: 1f8e3402f50b
Create Date: 2025-04-29 14:59:47.935164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe7b49e64f7'
down_revision: Union[str, None] = '1f8e3402f50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.String(), nullable=True))
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('refresh_tokens', 'refresh_token')
    # ### end Alembic commands ###
