"""remove inch from mounting

Revision ID: 264ba2fee3fa
Revises: aa5017e4f86a
Create Date: 2025-09-08 15:46:37.737414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264ba2fee3fa'
down_revision: Union[str, Sequence[str], None] = 'aa5017e4f86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mounting', 'inch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mounting', sa.Column('inch', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
