"""initial

Revision ID: 2c5e56e88ca6
Revises: 
Create Date: 2025-05-09 10:08:53.266468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5e56e88ca6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_bond', sa.String(), nullable=False),
    sa.Column('bond_description', sa.String(), nullable=False),
    sa.Column('bond_cooling', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bond_name_bond'), 'bond', ['name_bond'], unique=True)
    op.create_table('producer_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_producer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_name_name_producer'), 'producer_name', ['name_producer'], unique=True)
    op.create_table('shape_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shape_img_shape'), 'shape_img', ['shape'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('equipment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_equipment', sa.String(), nullable=False),
    sa.Column('name_producer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['name_producer'], ['producer_name.name_producer'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_model_name_equipment'), 'equipment_model', ['name_equipment'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('product_grinding_wheels',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('dimensions', sa.String(), nullable=False),
    sa.Column('name_bond', sa.String(), nullable=False),
    sa.Column('grid_size', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['name_bond'], ['bond.name_bond'], ),
    sa.ForeignKeyConstraint(['shape'], ['shape_img.shape'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_product_grinding_wheels_code'), 'product_grinding_wheels', ['code'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['product_grinding_wheels.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_code',
    sa.Column('name_equipment', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['product_grinding_wheels.code'], ),
    sa.ForeignKeyConstraint(['name_equipment'], ['equipment_model.name_equipment'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_equipment_code_code'), 'equipment_code', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_code_code'), table_name='equipment_code')
    op.drop_table('equipment_code')
    op.drop_table('cart')
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_product_grinding_wheels_code'), table_name='product_grinding_wheels')
    op.drop_table('product_grinding_wheels')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_equipment_model_name_equipment'), table_name='equipment_model')
    op.drop_table('equipment_model')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shape_img_shape'), table_name='shape_img')
    op.drop_table('shape_img')
    op.drop_index(op.f('ix_producer_name_name_producer'), table_name='producer_name')
    op.drop_table('producer_name')
    op.drop_index(op.f('ix_bond_name_bond'), table_name='bond')
    op.drop_table('bond')
    # ### end Alembic commands ###
