"""relationship

Revision ID: a24ac25a5843
Revises: 68e15d8da946
Create Date: 2025-04-15 16:34:20.068211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24ac25a5843'
down_revision: Union[str, None] = '68e15d8da946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_code', sa.String(), nullable=False))
    op.create_foreign_key(None, 'cart', 'catalog', ['product_code'], ['code'])
    op.drop_column('cart', 'dimensions')
    op.drop_column('cart', 'shape')
    op.drop_column('cart', 'code')
    op.drop_column('cart', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('images', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('shape', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('dimensions', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'product_code')
    # ### end Alembic commands ###
