"""fix bond

Revision ID: c18aee661060
Revises: 2c5e56e88ca6
Create Date: 2025-05-09 13:07:18.454464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18aee661060'
down_revision: Union[str, None] = '2c5e56e88ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_bond', sa.String(), nullable=False),
    sa.Column('bond_description', sa.String(), nullable=False),
    sa.Column('bond_cooling', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bond_name_bond'), 'bond', ['name_bond'], unique=True)
    op.create_table('producer_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_producer', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_name_name_producer'), 'producer_name', ['name_producer'], unique=True)
    op.create_table('shape_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shape_img_shape'), 'shape_img', ['shape'], unique=True)
    op.create_table('equipment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_equipment', sa.String(), nullable=False),
    sa.Column('name_producer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['name_producer'], ['producer_name.name_producer'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_model_name_equipment'), 'equipment_model', ['name_equipment'], unique=True)
    op.create_table('product_grinding_wheels',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('dimensions', sa.String(), nullable=False),
    sa.Column('name_bond', sa.String(), nullable=False),
    sa.Column('grid_size', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['name_bond'], ['bond.name_bond'], ),
    sa.ForeignKeyConstraint(['shape'], ['shape_img.shape'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_product_grinding_wheels_code'), 'product_grinding_wheels', ['code'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['product_grinding_wheels.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_code',
    sa.Column('name_equipment', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['product_grinding_wheels.code'], ),
    sa.ForeignKeyConstraint(['name_equipment'], ['equipment_model.name_equipment'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_equipment_code_code'), 'equipment_code', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_code_code'), table_name='equipment_code')
    op.drop_table('equipment_code')
    op.drop_table('cart')
    op.drop_index(op.f('ix_product_grinding_wheels_code'), table_name='product_grinding_wheels')
    op.drop_table('product_grinding_wheels')
    op.drop_index(op.f('ix_equipment_model_name_equipment'), table_name='equipment_model')
    op.drop_table('equipment_model')
    op.drop_index(op.f('ix_shape_img_shape'), table_name='shape_img')
    op.drop_table('shape_img')
    op.drop_index(op.f('ix_producer_name_name_producer'), table_name='producer_name')
    op.drop_table('producer_name')
    op.drop_index(op.f('ix_bond_name_bond'), table_name='bond')
    op.drop_table('bond')
    # ### end Alembic commands ###
