"""sharpening stones migration

Revision ID: 5a4e39fc47c2
Revises: 7ddc8d185b4e
Create Date: 2025-03-06 10:12:14.390668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4e39fc47c2'
down_revision = '7ddc8d185b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sharpening_stones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharpening_stones',
    sa.Column('article', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name_param1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit_param1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_param1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_param2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit_param2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_param2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_param3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit_param3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value_param3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('article', name='sharpening_stones_pkey')
    )
    # ### end Alembic commands ###
