"""renaming tables & routes.

Revision ID: bef0e32d87d2
Revises: 
Create Date: 2025-04-09 09:04:44.079761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef0e32d87d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('shape', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('shape', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_wood_items')
    op.drop_table('cart_items')
    op.drop_table('products')
    op.drop_table('woodworking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('woodworking',
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('shape', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dimensions', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name='woodworking_pkey')
    )
    op.create_table('products',
    sa.Column('article', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('line', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name_param1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_param1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value_param1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_param2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_param2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value_param2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_param3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_param3', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value_param3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_param4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_param4', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value_param4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_param5', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_param5', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value_param5', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_param6', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_param6', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value_param6', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_param7', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit_param7', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('value_param7', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('article', name='products_pkey')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cart_items_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cart_items_pkey')
    )
    op.create_table('cart_wood_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('shape', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dimensions', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cart_wood_items_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cart_wood_items_pkey')
    )
    op.drop_table('cart')
    op.drop_table('catalog')
    # ### end Alembic commands ###
